Web/Areas/Main/ViewModels/SharedViewModel.cs
using Core.Entites.WebSettings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Main.ViewModels
{
    public class SharedViewModel
    {
        public WebSettings WebSettings { get; set; }
    }
}

Web/Areas/Admin/Controllers/SlidesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core.Entites.Slide;
using Infrastructure.Data;
using Web.Areas.Admin.ViewModels.Slieds;
using Core.Interfaces;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SlidesController : Controller
    {
        private readonly IUnitOfWork<Slide> _slide;
        private readonly IHostingEnvironment _hosting;

        public SlidesController(IUnitOfWork<Slide> slide, IHostingEnvironment hosting)
        {
            _slide = slide;
            _hosting = hosting;
        }

        // GET: Certifications
        public IActionResult Index()
        {
            return View(_slide.Entity.GetAll());
        }

        // GET: Certifications/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slide = _slide.Entity.GetById(id);
            if (slide == null)
            {
                return NotFound();
            }

            return View(slide);
        }

        // GET: Certifications/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SlideViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.File != null)
                {
                    string uniqueFileName = ProcessUploadedFile(model);
                    Slide newSlide = new Slide
                    {
                        AddedDate = model.AddedDate,
                        Text1 = model.Text1,
                        Text2 = model.Text2,
                        SlideURL = uniqueFileName
                    };
                    _slide.Entity.Insert(newSlide);
                    _slide.Save();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }

        // GET: Certifications/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var certification = _slide.Entity.GetById(id);

            if (certification == null)
            {
                return NotFound();
            }

            SlideEditViewModel slideEditViewModel = new SlideEditViewModel
            {
                Id = certification.Id,
                AddedDate = certification.AddedDate,
                Text1 = certification.Text1,
                Text2 = certification.Text2,
                ExstingSlideURL = certification.SlideURL
            };

            return View(slideEditViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SlideEditViewModel model)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    Slide slide = _slide.Entity.GetById(model.Id);
                    slide.AddedDate = model.AddedDate;
                    slide.Text1 = model.Text1;
                    slide.Text2 = model.Text2;

                    if (model.File != null)
                    {
                        if (model.ExstingSlideURL != null)
                        {
                            string filePath = Path.Combine(_hosting.WebRootPath, @"images\home\slide", model.ExstingSlideURL);
                            System.IO.File.Delete(filePath);
                        }
                        slide.SlideURL = ProcessUploadedFile(model);
                    }

                    _slide.Entity.Update(slide);
                    _slide.Save();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SlideExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("index");
            }
            return View(model);
        }

        // GET: Certifications/Delete/5
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slide = _slide.Entity.GetById(id);
            if (slide == null)
            {
                return NotFound();
            }

            return View(slide);
        }

        // POST: Certifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _slide.Entity.Delete(id);
            _slide.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool SlideExists(Guid id)
        {
            return _slide.Entity.GetAll().Any(e => e.Id == id);
        }

        private string ProcessUploadedFile(SlideViewModel model)
        {
            string uniqueFileName = null;
            if (model.File != null)
            {
                string uploadsFolder = Path.Combine(_hosting.WebRootPath, @"images\home\slide");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.File.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.File.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

Web/Areas/Main/Controllers/AboutusController.cs
using Core.Entites.Aboutus;
using Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Main.ViewModels;

namespace Web.Areas.Main.Controllers
{
    [AllowAnonymous]
    [Area("Main")]
    public class AboutusController : Controller
    {
        private readonly IUnitOfWork<Aboutus> _aboutus;
        private readonly IUnitOfWork<Certification> _certification;
        private readonly IUnitOfWork<QualityPolicy> _qualityPolicy;

        public AboutusController(
            IUnitOfWork<Aboutus> aboutus,
            IUnitOfWork<Certification> certification,
            IUnitOfWork<QualityPolicy> qualitypolicy
            )
        {
            _aboutus = aboutus;
            _certification = certification;
            _qualityPolicy = qualitypolicy;
        }
        public IActionResult Index()
        {
            var aboutusPageViewModel = new AboutusPageViewModel
            {
                Aboutus = _aboutus.Entity.GetAll().FirstOrDefault(),
                Certifications = _certification.Entity.GetAll().ToList(),
                QualityPolicies = _qualityPolicy.Entity.GetAll().ToList()
            };

            return View(aboutusPageViewModel);
        }
    }
}

Web/Areas/Main/Controllers/ContactusController.cs
using Core.Entites.Contactus;
using Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Main.Controllers
{
    [AllowAnonymous]
    [Area("Main")]

    public class ContactusController : Controller
    {
        private readonly IUnitOfWork<Contactus> _contactus;

        public ContactusController(IUnitOfWork<Contactus> contactus)
        {
            _contactus = contactus;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveContact(Contactus model)
        {
            if (ModelState.IsValid)
            {
                Contactus contactus = new Contactus
                {
                    MessageTitle = model.MessageTitle,
                    Email = model.Email,
                    MessageContent = model.MessageContent,
                    Name = model.Name,
                    Phone = model.Phone
                };

                _contactus.Entity.Insert(contactus);
                _contactus.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

    }
}

Web/Areas/Main/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Main.Controllers
{
    [AllowAnonymous]
    [Area("Main")]

    public class ServicesController : Controller
    {

        public IActionResult Geotechnical()
        {
            return View();
        }
        public IActionResult Material()
        {
            return View();
        }
        public IActionResult Water()
        {
            return View();
        }
        public IActionResult Evaluation()
        {
            return View();
        }
        public IActionResult Masonary()
        {
            return View();
        }
    }
}

Web/Areas/Admin/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- For IE -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- For Resposive Device -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- For Window Tab Color -->
    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#061948">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#061948">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-status-bar-style" content="#061948">
    <title>NEWTESTLAB</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="56x56" href="~/images/home/webSetting/icon.png">
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <link rel="stylesheet" href="~/fonts/font-awesome/css/all.min.css">
    <!-- Web style sheets -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- Main style sheet -->
    <link rel="stylesheet" href="~/css/adminlte.css">
    <!-- Admin Panel Style Sheet -->
    <link rel="stylesheet" type="text/css" href="~/css/admin-panel.css">
    <!-- Admin Panel Style Sheet -->
    <link rel="stylesheet" href="~/css/admin-panel.css">
</head>
<body>
    <div class="hold-transition sidebar-mini">
        <!-- Site wrapper -->
        <div class="wrapper">
            <!-- Navbar -->
            <nav class="main-header navbar navbar-expand navbar-white navbar-light">
                <!-- Left navbar links -->
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                    </li>

                    <li class="nav-item d-none d-sm-inline-block">
                        <a asp-area="Main" asp-action="Index" asp-controller="Home" class="nav-link">Home</a>
                    </li>

                </ul>
                <ul class="navbar-nav ml-auto">

                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item d-none d-sm-inline-block">
                            <form method="post" asp-area="admin" asp-action="Logout" asp-controller="Account">
                                <button type="submit" class="nav-link btn btn-link py-0">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item d-none d-sm-inline-block">
                            <a asp-area="admin" asp-action="Login" asp-controller="account" class="nav-link">Login</a>
                        </li>
                    }


                </ul>
            </nav>
            <!-- /.navbar -->
            <!-- Main Sidebar Container -->
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <!-- Brand Logo -->
                <a href="#" class="brand-link">
                    <span class="brand-text font-weight-light">NEWTESTLAB</span>
                </a>

                <!-- Sidebar -->
                <div class="sidebar">
                    <!-- Sidebar user (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                            <img src="~/images/admin-panel/user-01.jpg" class="img-circle elevation-2" alt="User Image">
                        </div>
                        <div class="info">
                            <a href="#" class="d-block">Qusai Aburayyn</a>
                        </div>
                    </div>

                    <!-- SidebarSearch Form -->
                    <div class="form-inline">
                        <div class="input-group" data-widget="sidebar-search">
                            <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-sidebar">
                                    <i class="fas fa-search fa-fw"></i>
                                </button>
                            </div>
                        </div>
                    </div>

                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            <li class="nav-item">
                                <a asp-area="Admin" asp-action="Index" asp-controller="Contactus" class="nav-link">
                                    <i class="nav-icon far fa-envelope"></i>
                                    <p>Mail Box</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-action="Index" asp-controller="WebSettings" class="nav-link">
                                    <i class="nav-icon  fas fa-sliders-h"></i>
                                    <p>Website Settings</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-action="Index" asp-controller="SocialMediaAddresses" class="nav-link">
                                    <i class="nav-icon fas fa-share-alt"></i>
                                    <p>Social Media</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-action="Index" asp-controller="Slides" class="nav-link">
                                    <i class="nav-icon fab fa-slideshare"></i>
                                    <p>Slides</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>About us<i class="right fas fa-angle-left"></i></p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a asp-area="Admin" asp-action="Index" asp-controller="Aboutus" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Main Content</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-area="Admin" asp-action="Index" asp-controller="Certifications" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Certfications</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-area="Admin" asp-action="Index" asp-controller="QualityPolicies" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Quality Policy</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-action="Index" asp-controller="Services" class="nav-link">
                                    <i class="nav-icon fas fa-th"></i>
                                    <p>Services</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="Admin" asp-action="Index" asp-controller="SpecialServices" class="nav-link">
                                    <i class="nav-icon far fa-star"></i>
                                    <p>Special Services</p>
                                </a>
                            </li>

                            @if (signInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a asp-area="Admin" asp-action="Register" asp-controller="Account" class="nav-link">
                                        <i class="nav-icon fas fa-user-plus"></i>
                                        <p>Register New User</p>
                                    </a>
                                </li>
                            }

                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
                <!-- /.sidebar -->
            </aside>

            <div>
                @RenderBody()
            </div>

            <footer class="main-footer">
                <div class="float-right d-none d-sm-block">
                    <b>Technical Support :</b> 0569-441-004
                </div>
                &copy; Copyrights 2021. All Rights Reserved. <strong>NEWTESTLAB.</strong>
            </footer>

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>
        <!-- ./wrapper -->
    </div>
    <!-- jQuery -->
    <script src="~/vendor/jquery.2.2.3.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/vendor/bootstrap/css/bootstrap.min.css"></script>
    <!-- Admin-Panel-->
    <script src="~/js/adminlte.min.js"></script>
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: true);
    }
</body>
</html>

Web/Areas/Admin/Views/Shared/_Layout1.cshtml
@inject SignInManager<ApplicationUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- For IE -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- For Resposive Device -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- For Window Tab Color -->
    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#061948">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#061948">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-status-bar-style" content="#061948">
    <title>NEWTESTLAB</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="56x56" href="~/images/home/webSetting/icon.png">
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <link rel="stylesheet" href="~/fonts/font-awesome/css/all.min.css">
    <!-- Web style sheets -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- Main style sheet -->
    <link rel="stylesheet" href="~/css/adminlte.css">
    <!-- Admin Panel Style Sheet -->
    <link rel="stylesheet" type="text/css" href="~/css/admin-panel.css">
    <!-- Admin Panel Style Sheet -->
    <link rel="stylesheet" href="~/css/admin-panel.css">
</head>
<body>
    <div class="hold-transition sidebar-mini">

        @RenderBody()

    </div>
    <!-- jQuery -->
    <script src="~/vendor/jquery.2.2.3.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/vendor/bootstrap/css/bootstrap.min.css"></script>
    <!-- Admin-Panel-->
    <script src="~/js/adminlte.min.js"></script>
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: true);
    }
</body>
</html>