Web/Areas/Main/ViewModels/HomeViewModel.cs
using Core.Entites.Aboutus;
using Core.Entites.Contactus;
using Core.Entites.Service;
using Core.Entites.Slide;
using Core.Entites.SpecialService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Main.ViewModels
{
    public class HomeViewModel
    {
        public List<Slide> Slides { get; set; }
        public Aboutus Aboutus { get; set; }
        public List<Service> Services { get; set; }
        public List<SpecialService> SpecialServices { get; set; }
    }
}

Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Areas/Admin/Controllers/SpecialServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core.Entites.SpecialService;
using Infrastructure.Data;
using Core.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Web.Areas.Admin.ViewModels.SpecialServices;
using System.IO;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecialServicesController : Controller
    {
        private readonly IUnitOfWork<SpecialService> _specialService;
        private readonly IHostingEnvironment _hosting;

        public SpecialServicesController(IUnitOfWork<SpecialService> specialService, IHostingEnvironment hosting)
        {
            _specialService = specialService;
            _hosting = hosting;
        }

        // GET: Services/Services
        public IActionResult Index()
        {
            return View(_specialService.Entity.GetAll());
        }

        // GET: Services/Services/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialService = _specialService.Entity.GetById(id);
            if (specialService == null)
            {
                return NotFound();
            }

            return View(specialService);
        }

        // GET: Services/Services/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SpecialServiceCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadedFile(model);
                SpecialService newSpecialService = new SpecialService
                {
                    Title = model.Title,
                    AddedDate = model.AddedDate,
                    Content = model.Content,
                    ImageURL = uniqueFileName,
                    ActionName=model.ActionName
                };
                _specialService.Entity.Insert(newSpecialService);
                _specialService.Save();
                return RedirectToAction("index");
            }
            return View();
        }

        // GET: Services/Services/Edit/5
        public IActionResult Edit(Guid? id)
        {
            var speciaService = _specialService.Entity.GetById(id);
            SpecialServiceEditViewModel specialServiceEditViewModel = new SpecialServiceEditViewModel
            {
                Id = speciaService.Id,                
                Title = speciaService.Title,
                AddedDate = speciaService.AddedDate,
                Content = speciaService.Content,
                ExistingPhotoPath = speciaService.ImageURL,
                ActionName=speciaService.ActionName
            };
            return View(specialServiceEditViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SpecialServiceEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                SpecialService specialService = _specialService.Entity.GetById(model.Id);
                specialService.Title = model.Title;
                specialService.AddedDate = model.AddedDate;
                specialService.Content = model.Content;
                specialService.ActionName = model.ActionName;
                if (model.File != null)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(_hosting.WebRootPath, @"images\specialServices", model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    specialService.ImageURL = ProcessUploadedFile(model);
                }

                _specialService.Entity.Update(specialService);
                _specialService.Save();
                return RedirectToAction("index");
            }
            return View();
        }

        // GET: Services/Services/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = _specialService.Entity.GetById(id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // POST: Services/Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _specialService.Entity.Delete(id);
            _specialService.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool SpecialServiceExists(Guid id)
        {
            return _specialService.Entity.GetAll().Any(e => e.Id == id);
        }

        private string ProcessUploadedFile(SpecialServiceCreateViewModel model)
        {
            string uniqueFileName = null;
            if (model.File != null)
            {
                string uploadsFolder = Path.Combine(_hosting.WebRootPath, @"images\specialServices");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.File.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.File.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

Web/Areas/Main/Controllers/ContactusController.cs
using Core.Entites.Contactus;
using Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Main.Controllers
{
    [AllowAnonymous]
    [Area("Main")]

    public class ContactusController : Controller
    {
        private readonly IUnitOfWork<Contactus> _contactus;

        public ContactusController(IUnitOfWork<Contactus> contactus)
        {
            _contactus = contactus;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveContact(Contactus model)
        {
            if (ModelState.IsValid)
            {
                Contactus contactus = new Contactus
                {
                    MessageTitle = model.MessageTitle,
                    Email = model.Email,
                    MessageContent = model.MessageContent,
                    Name = model.Name,
                    Phone = model.Phone
                };

                _contactus.Entity.Insert(contactus);
                _contactus.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

    }
}

Web/Areas/Main/Controllers/HomeController.cs
using Core.Entites.Aboutus;
using Core.Entites.Contactus;
using Core.Entites.Service;
using Core.Entites.Slide;
using Core.Entites.SpecialService;
using Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Main.ViewModels;

namespace Web.Areas.Main.Controllers
{
    [AllowAnonymous]
    [Area("Main")]
    public class HomeController : Controller
    {
        private readonly IUnitOfWork<Slide> _slide;
        private readonly IUnitOfWork<Aboutus> _aboutus;
        private readonly IUnitOfWork<Service> _service;
        private readonly IUnitOfWork<SpecialService> _specialService;


        public HomeController(
            IUnitOfWork<Slide> slide,
            IUnitOfWork<Aboutus> aboutus,
            IUnitOfWork<Service> service,
            IUnitOfWork<SpecialService> specialService)
        {
            _slide = slide;
            _aboutus = aboutus;
            _service = service;
            _specialService = specialService;
        }
        public IActionResult Index()
        {
            var homeViewModel = new HomeViewModel
            {
                Slides = _slide.Entity.GetAll().ToList(),
                Aboutus = _aboutus.Entity.GetAll().FirstOrDefault(),
                Services = _service.Entity.GetAll().ToList(),
                SpecialServices = _specialService.Entity.GetAll().ToList(),
            };
            return View(homeViewModel);
        }
    }
}

Web/Areas/Main/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Main.Controllers
{
    [AllowAnonymous]
    [Area("Main")]

    public class ServicesController : Controller
    {

        public IActionResult Geotechnical()
        {
            return View();
        }
        public IActionResult Material()
        {
            return View();
        }
        public IActionResult Water()
        {
            return View();
        }
        public IActionResult Evaluation()
        {
            return View();
        }
        public IActionResult Masonary()
        {
            return View();
        }
    }
}

Web/Areas/Main/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "index";
}




<!--
==============================================
    Theme Main Banner
==============================================
-->
<div class="section-spacing">
    <div id="theme-main-banner" class="banner-one">
        @foreach (var slide in Model.Slides)
        {
            <div class="" data-src="@Url.Content("~/images/home/slide/" + slide.SlideURL)">
                <div class="camera_caption">
                    <div class="container">
                        <h1 class="wow fadeInUp animated" data-wow-delay="0.2s">@slide.Text1 <br>@slide.Text2</h1>
                        <a asp-area="Main" asp-action="Index" asp-controller="Contactus" class="theme-button-one wow fadeInUp animated" data-wow-delay="0.39s">CONTACT US</a>
                    </div>
                </div>
            </div>
        }
    </div> <!-- /#theme-main-banner -->
</div>

<!--
=============================================
    About Company
==============================================
-->
<div class="about-compnay section-spacing">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-12"><img src="~/images/aboutus/@Model.Aboutus.ImageURL" alt=""></div>
            <div class="col-lg-6 col-12">
                <div class="text">
                    <div class="theme-title-one">
                        <h2>About Our Company</h2>
                        <div class="about-text">
                            <p class="card-text">
                                @Model.Aboutus.Para1
                            </p>
                        </div>
                    </div> <!-- /.theme-title-one -->
                    <ul class="mission-goal clearfix">
                        <li>
                            <i class="icon flaticon-star"></i>
                            <h4>Vision</h4>
                        </li>
                        <li>
                            <i class="icon flaticon-medal"></i>
                            <h4>Missions</h4>
                        </li>
                        <li>
                            <i class="icon flaticon-target"></i>
                            <h4>Goals</h4>
                        </li>
                    </ul> <!-- /.mission-goal -->
                </div> <!-- /.text -->
            </div> <!-- /.col- -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</div> <!-- /.about-compnay -->
<!--
=============================================
    Feature Banner
==============================================
-->
<div class="feature-banner">
    <div class="opacity">
        <div class="container">
            <h2>We provide high quality services &amp; innovative solutions for the realiable growth</h2>
        </div> <!-- /.container -->
    </div> <!-- /.opacity -->
</div> <!-- /.feature-banner -->
<!--
=============================================
    Core Values
==============================================
-->
<div class="core-values">
    <div class="container">
        <div class="theme-title-one">
            <h2>SERVICES</h2>
        </div> <!-- /.theme-title-one -->
        <div class="wrapper">
            <div class="core-value-slider">

                @foreach (var service in Model.Services)
                {
                    <div class="item">
                        <div class="single-value-block">
                            <div class="image-box">
                                <img src="~/images/service/@service.ImageURL" alt="">
                                <div class="overlay"><a asp-area="Main" asp-action="@service.ActionName" asp-controller="Services" class="theme-button-one">READ MORE</a></div>
                            </div> <!-- /.image-box -->
                            <div class="text">
                                <h5><a asp-area="Main" asp-action="@service.ActionName" asp-controller="Services">@service.Title</a></h5>
                                <div class="card-text">
                                    <p>
                                        @service.Content
                                    </p>
                                </div> <!-- /.card-text -->
                                <a asp-area="Main" asp-action="@service.ActionName" asp-controller="Services" class="read-more">READ MORE</a>
                            </div> <!-- /.text -->
                        </div> <!-- /.single-value-block -->
                    </div> <!-- /.col- -->
                }


            </div> <!-- /.core-value-slider -->
        </div> <!-- /.wrapper -->
    </div> <!-- /.container -->
</div> <!-- /.core-values -->
<!--


=============================================
    Feature Banner
==============================================
-->
<div class="feature-banner">
    <div class="opacity">
        <div class="container">
            <h2>We provide high quality services &amp; innovative solutions for the realiable growth</h2>
        </div> <!-- /.container -->
    </div> <!-- /.opacity -->
</div> <!-- /.feature-banner -->
<!--
=============================================
    Core Values
==============================================
-->
<div class="core-values">
    <div class="container">
        <div class="theme-title-one">
            <h2>SPECIAL SERVICES</h2>
        </div> <!-- /.theme-title-one -->
        <div class="wrapper">
            <div class="core-value-slider">

                @foreach (var specialService in Model.SpecialServices)
                {
                    <div class="item">
                        <div class="single-value-block">
                            <div class="image-box">
                                <img src="~/images/specialServices/@specialService.ImageURL" alt="">
                                <div class="overlay"><a asp-area="Main" asp-action="@specialService.ActionName" asp-controller="SpecialServices" class="theme-button-one">READ MORE</a></div>
                            </div> <!-- /.image-box -->
                            <div class="text">
                                <h5><a asp-area="Main" asp-action="@specialService.ActionName" asp-controller="SpecialServices">@specialService.Title</a></h5>
                                <div class="card-text">
                                    <p>
                                        @specialService.Content
                                    </p>
                                </div> <!-- /.card-text -->
                                <a asp-area="Main" asp-action="@specialService.ActionName" asp-controller="SpecialServices" class="read-more">READ MORE</a>
                            </div> <!-- /.text -->
                        </div> <!-- /.single-value-block -->
                    </div> <!-- /.col- -->
                }

            </div> <!-- /.core-value-slider -->
        </div> <!-- /.wrapper -->
    </div> <!-- /.container -->
</div> <!-- /.core-values -->