Web/Areas/Main/ViewModels/SharedViewModel.cs
using Core.Entites.WebSettings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Main.ViewModels
{
    public class SharedViewModel
    {
        public WebSettings WebSettings { get; set; }
    }
}

Web/Areas/Main/Controllers/AboutusController.cs
using Core.Entites.Aboutus;
using Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Main.ViewModels;

namespace Web.Areas.Main.Controllers
{
    [AllowAnonymous]
    [Area("Main")]
    public class AboutusController : Controller
    {
        private readonly IUnitOfWork<Aboutus> _aboutus;
        private readonly IUnitOfWork<Certification> _certification;
        private readonly IUnitOfWork<QualityPolicy> _qualityPolicy;

        public AboutusController(
            IUnitOfWork<Aboutus> aboutus,
            IUnitOfWork<Certification> certification,
            IUnitOfWork<QualityPolicy> qualitypolicy
            )
        {
            _aboutus = aboutus;
            _certification = certification;
            _qualityPolicy = qualitypolicy;
        }
        public IActionResult Index()
        {
            var aboutusPageViewModel = new AboutusPageViewModel
            {
                Aboutus = _aboutus.Entity.GetAll().FirstOrDefault(),
                Certifications = _certification.Entity.GetAll().ToList(),
                QualityPolicies = _qualityPolicy.Entity.GetAll().ToList()
            };

            return View(aboutusPageViewModel);
        }
    }
}

Web/Areas/Main/Controllers/ContactusController.cs
using Core.Entites.Contactus;
using Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Main.Controllers
{
    [AllowAnonymous]
    [Area("Main")]

    public class ContactusController : Controller
    {
        private readonly IUnitOfWork<Contactus> _contactus;

        public ContactusController(IUnitOfWork<Contactus> contactus)
        {
            _contactus = contactus;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveContact(Contactus model)
        {
            if (ModelState.IsValid)
            {
                Contactus contactus = new Contactus
                {
                    MessageTitle = model.MessageTitle,
                    Email = model.Email,
                    MessageContent = model.MessageContent,
                    Name = model.Name,
                    Phone = model.Phone
                };

                _contactus.Entity.Insert(contactus);
                _contactus.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

    }
}

Web/Areas/Main/ViewComponents/FooterViewComponent.cs
using Core.Entites.WebSettings;
using Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Main.ViewModels;

namespace Web.Areas.Main.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly IUnitOfWork<WebSettings> _webSettings;

        public FooterViewComponent(
            IUnitOfWork<WebSettings> webSettings)
        {
            _webSettings = webSettings;
        }

        public IViewComponentResult Invoke()
        {
            var sharedViewModel = new SharedViewModel
            {
                WebSettings = _webSettings.Entity.GetAll().First()
            };
            return View(sharedViewModel);
        }
    }
}

Web/Areas/Main/ViewComponents/SharedViewComponent.cs
using Core.Entites.WebSettings;
using Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Main.ViewModels;

namespace Web.Areas.Main.ViewComponents
{
    public class SharedViewComponent : ViewComponent
    {
        private readonly IUnitOfWork<WebSettings> _webSettings;

        public SharedViewComponent(
            IUnitOfWork<WebSettings> webSettings)
        {
            _webSettings = webSettings;
        }

        public IViewComponentResult Invoke(Guid? id)
        {
            var sharedViewModel = new SharedViewModel
            {
                WebSettings = _webSettings.Entity.GetAll().First()
            };
            return View(sharedViewModel);
        }
    }
}

Web/Areas/Main/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- For IE -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- For Resposive Device -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- For Window Tab Color -->
    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#061948">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#061948">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-status-bar-style" content="#061948">
    <title>NEWTESTLAB</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="56x56" href="~/images/home/webSetting/icon.png">
    <link rel="stylesheet" href="fonts/font-awesome/css/all.min.css">
    <!-- Web style sheets -->
    <!-- Main style sheet -->
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <!-- Override style sheet -->
    <link rel="stylesheet" type="text/css" href="~/css/overrideStyle.css">
    <!-- responsive style sheet -->
    <link rel="stylesheet" type="text/css" href="~/css/responsive.css">
</head>
<body>
    <div class="main-page-wrapper">

        <!--
    ===================================================
        Loading Transition
    ====================================================
    -->
        <div id="loader-wrapper">
            <div id="loader"></div>
        </div>


        <!--
    =============================================
        Theme Header One
    ==============================================
    -->

        <header class="header-one">
            <div class="top-header">
                @await Component.InvokeAsync("Shared")
            </div> <!-- /.top-header -->

            <div class="theme-menu-wrapper">
                <div class="container">
                    <div class="bg-wrapper clearfix">
                        <!-- ============== Menu Warpper ================ -->
                        <div class="menu-wrapper float-left">
                            <nav id="mega-menu-holder" class="clearfix">
                                <ul class="clearfix">
                                    <li class="active"><a asp-area="Main" asp-action="index" asp-controller="Home">Home</a></li>
                                    <li><a asp-area="Main" asp-action="index" asp-controller="Aboutus">About Us</a></li>
                                    <li>
                                        <a>Services</a>
                                        <ul class="dropdown">
                                            @await Component.InvokeAsync("Services")
                                        </ul>
                                    </li>
                                    <li>
                                        <a>Special Services</a>
                                        <ul class="dropdown">
                                            @await Component.InvokeAsync("SpecialServices")
                                        </ul>
                                    </li>
                                    <li><a asp-area="Main" asp-action="index" asp-controller="Contactus">contact</a></li>
                                </ul>
                            </nav> <!-- /#mega-menu-holder -->
                        </div> <!-- /.menu-wrapper -->

                        <div class="right-widget float-right">
                            <ul>
                                <li style="margin-right:25px" class="social-icon">
                                    <ul>
                                        @await Component.InvokeAsync("SocialMediaAddresses")
                                    </ul>
                                </li>
                            </ul>
                        </div> <!-- /.right-widget -->
                    </div> <!-- /.bg-wrapper -->
                </div> <!-- /.container -->
            </div> <!-- /.theme-menu-wrapper -->
        </header> <!-- /.header-one -->




        <div>
            @RenderBody()
        </div>

        <!--
    =====================================================
        Footer
    =====================================================
    -->
        <footer class="theme-footer-two">
            <div class="top-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 col-sm-6 col-12 logo-widget">
                            @await Component.InvokeAsync("FooterLogo")
                            <ul class="social-icon">
                                @await Component.InvokeAsync("SocialMediaAddresses")
                            </ul>
                        </div> <!-- /.logo-widget -->
                        <div class="col-lg-2 col-sm-6 col-12 contact-widget">
                            <h6 class="title">EXPLORE</h6>
                            <div class="ex-plore">
                                <ul>
                                    <li><i class="bi bi-circle"></i><a asp-area="Main" asp-action="index" asp-controller="Home">Home</a></li>
                                    <li><i class="bi bi-circle"></i><a asp-area="Main" asp-action="index" asp-controller="Aboutus">About us</a></li>
                                    <li><i class="bi bi-circle"></i><a asp-area="Main" asp-action="index" asp-controller="Contactus">Contact us</a></li>
                                </ul>
                            </div>
                        </div> <!-- /.footer-list -->
                        <div class="col-lg-3 col-sm-6 col-12 footer-gallery contact-widget">
                            <h6 class="title">Downloads</h6>
                            <div class="wrapper">
                                <div class="row">
                                    <ul>
                                        @await Component.InvokeAsync("PdfFiles")
                                    </ul>
                                </div>
                            </div>
                        </div> <!-- /.footer-gallery -->

                        <div class="col-lg-3 col-sm-6 col-12 contact-widget">
                            <h6 class="title">CONTACT</h6>
                            <ul>
                                @await Component.InvokeAsync("Footer")
                            </ul>
                        </div> <!-- /.contact-widget -->
                    </div> <!-- /.row -->
                </div> <!-- /.container -->
            </div> <!-- /.top-footer -->
            <div class="bottom-footer">
                <div class="container">
                    <p>&copy; Copyrights 2021. All Rights Reserved.</p>
                </div>
            </div> <!-- /.bottom-footer -->
        </footer> <!-- /.theme-footer-two -->
        <!-- Scroll Top Button -->
        <button class="scroll-top tran3s">
            <i class="fa fa-angle-up" aria-hidden="true"></i>
        </button>


        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <!-- jQuery -->
        <script src="~/vendor/jquery.2.2.3.min.js"></script>
        <!-- Popper js -->
        <script src="~/vendor/popper.js/popper.min.js"></script>
        <!-- Bootstrap JS -->
        <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
        <!-- Camera Slider -->
        <script src='~/vendor/Camera-master/scripts/jquery.mobile.customized.min.js'></script>
        <script src='~/vendor/Camera-master/scripts/jquery.easing.1.3.js'></script>
        <script src='~/vendor/Camera-master/scripts/camera.min.js'></script>
        <!-- menu  -->
        <script src="~/vendor/menu/src/js/jquery.slimmenu.js"></script>
        <!-- WOW js -->
        <script src="~/vendor/WOW-master/dist/wow.min.js"></script>
        <!-- owl.carousel -->
        <script src="~/vendor/owl-carousel/owl.carousel.min.js"></script>
        <!-- js count to -->
        <script src="~/vendor/jquery.appear.js"></script>
        <script src="~/vendor/jquery.countTo.js"></script>
        <!-- Fancybox -->
        <script src="~/vendor/fancybox/dist/jquery.fancybox.min.js"></script>
        <!-- Theme js -->
        <script src="~/js/theme.js"></script>
    </div> <!-- /.main-page-wrapper -->

</body>
</html>